package:
  name: libtorrent
  version: 2.0.10
  epoch: 0
  description: "an efficient feature complete C++ bittorrent implementation"
  target-architecture:
    - all
  dependencies:
    runtime: []

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - build-base
      - busybox
      - cmake
      - git
      - ninja-build
      - boost-dev
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/arvidn/libtorrent.git
      tag: v${{package.version}}
      expected-commit: 74bc93a37a5e31c78f0aa02037a68fb9ac5deb41
      recurse-submodules: true

  - uses: cmake/configure
    with:
      opts: '-D CMAKE_CXX_STANDARD=20 -G Ninja'

  - uses: cmake/build
  
  - uses: cmake/install

  - uses: strip

subpackages:
  - name: libtorrent-dev
    pipeline:
      - uses: split/dev
