name: Build action

on: 
  push:
  schedule:
    - cron: '15 3 * * *'  # every day at 03:15 (just wanted to avoid midnight)

jobs:
  build:
    name: Build qbtitorrent image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo ::set-output name=date::$(date -u +%Y%m%d)
          echo ::set-output name=epoch::$(date -u +%s)
        shell: bash

      - uses: actions/checkout@main
      - uses: sigstore/cosign-installer@main

      - uses: chainguard-dev/actions/setup-melange@main
        with:
          version: v0.14.10
      - uses: chainguard-dev/actions/melange-keygen@main
        with:
          signing-key-path: ${{ github.workspace }}/melange.rsa
      - uses: chainguard-dev/actions/melange-build-pkg@main
        with:
          multi-config: "libtorrent.yaml,qt6-qttools.yaml,qbittorrent.yaml"
          sign-with-key: true
          signing-key-path: ${{ github.workspace }}/melange.rsa
          empty-workspace: true
          repository-path: ${{ github.workspace }}/packages

      - uses: distroless/actions/apko-publish@main
        with:
          archs: x86_64
          repository-append: ${{ github.workspace }}/packages
          keyring-append: ${{ github.workspace }}/melange.rsa.pub
          tag: ghcr.io/${{ github.repository }}:latest
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
